import {KyivClock} from './kyiv-clock.mjs';
import {kyivParts,silenceWindow,schoolState,durationLabel,hhmmSeconds} from './time-core.mjs';
import {SilencePlayer} from './minute-of-silence.mjs';
const C=window.SchoolScheduleConfig,D=C.dayOrder,B=C.bellSchedule;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clock=new KyivClock();
let today=kyivParts(clock.now()).weekday-1;
const params=new URLSearchParams(location.search);
const requestedGrade=(params.get('class')||'').replace(' клас','').trim();
let grade=/^[5-9]$/.test(requestedGrade)?requestedGrade:'all';
let day=params.has('day')&&D.some(d=>d.id===params.get('day'))?D.findIndex(d=>d.id===params.get('day')):today>=0&&today<5?today:0;
let view=params.get('view')==='week'||location.pathname.endsWith('class.html')?'week':'day';
let section=location.hash==='#bells'?'bells':'schedule',subject='',dayFilters={},autoDay=!params.has('day');
const timeFormatter=new Intl.DateTimeFormat('uk-UA',{timeZone:'Europe/Kyiv',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});
const dateFormatter=new Intl.DateTimeFormat('uk-UA',{timeZone:'Europe/Kyiv',weekday:'long',day:'numeric',month:'long'});
let lastSecond='',lastLive='',lastDate='';
const subjects=[...new Set(C.scheduleRows.flatMap(r=>r.classes).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'uk'));
$('#subject-filter').innerHTML='<option value="">Усі предмети</option>'+subjects.map(s=>'<option>'+esc(s)+'</option>').join('');
function color(s){if(/мова|література/.test(s))return '#436dde';if(/Математика|Алгебра|Геометрія|Інформатика|Фізика/.test(s))return '#8163bd';if(/Біологія|Географія|Природознавство|Хімія/.test(s))return '#3e927d';if(/мистецтво|Мистецтво|Технології/.test(s))return '#c48733';if(/Фізична|здоров/.test(s))return '#47889b';return '#b96b72';}
function subjectCell(s){return s?'<button type="button" class="subject" data-subject="'+esc(s)+'" style="--subject-color:'+color(s)+'" title="Виділити предмет: '+esc(s)+'">'+esc(s)+'</button>':'<span class="empty" aria-label="Уроку немає">—</span>';}
function table(index,allClasses=false){const columns=allClasses||grade==='all'?[0,1,2,3,4]:[Number(grade)-5];const rows=C.scheduleRows.filter(r=>r.day===D[index].label);
return '<div class="table-wrap" tabindex="0" role="region" aria-label="'+D[index].label+' — розклад уроків"><table class="schedule-table '+(columns.length===1?'single-class':'')+'"><caption class="sr-only">'+D[index].label+' — '+(columns.length===1?grade+' клас':'5–9 класи')+'</caption><thead><tr><th scope="col">Урок / час</th>'+columns.map(i=>'<th scope="col" data-grade-head="'+(i+5)+'"><a class="class-link" href="class.html?class='+encodeURIComponent(C.classes[i])+'" data-grade-link="'+(i+5)+'">'+'<span class="class-number">'+(i+5)+'</span> клас <span aria-hidden="true">↗</span></a></th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr data-row-day="'+index+'" data-lesson="'+r.lesson+'"><th scope="row"><span class="lesson-number">'+r.lesson+'</span><span class="lesson-time">'+B[r.lesson-1].start+'–'+B[r.lesson-1].end+'</span><span class="row-state"></span></th>'+columns.map(i=>'<td data-grade="'+(i+5)+'">'+subjectCell(r.classes[i])+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function weekMatrix(){return '<div class="table-wrap"><table class="schedule-table"><thead><tr><th>Урок / час</th>'+D.map(d=>'<th>'+d.label+'</th>').join('')+'</tr></thead><tbody>'+B.map((b,i)=>'<tr><th>'+b.lesson+'<span class="lesson-time">'+b.start+'–'+b.end+'</span></th>'+D.map(d=>'<td>'+subjectCell(C.scheduleRows.find(r=>r.day===d.label&&r.lesson===b.lesson).classes[Number(grade)-5])+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function perDayFilter(i){return '<label class="day-subject-label"><span class="sr-only">Предмет: '+D[i].label+'</span><select data-day-subject="'+i+'"><option value="">Усі предмети цього дня</option>'+[...new Set(C.scheduleRows.filter(r=>r.day===D[i].label).flatMap(r=>r.classes).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'uk')).map(s=>'<option'+(dayFilters[i]===s?' selected':'')+'>'+esc(s)+'</option>').join('')+'</select></label>';}
function render(){today=kyivParts(clock.now()).weekday-1;
$('#day-tabs').innerHTML=D.map((d,i)=>'<button type="button" data-day="'+i+'" aria-pressed="'+(view==='day'&&i===day)+'">'+d.label+(i===today?'<span class="today-dot" aria-label="сьогодні"></span>':'')+'</button>').join('');
$$('[data-class]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.class===grade)));
$$('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));
$('#schedule-caption').textContent=(view==='week'?'Понеділок — п’ятниця':D[day].label)+(view==='day'&&day===today?' · Сьогодні':'')+' · '+(grade==='all'?'5–9 класи':grade+' клас');
$('#schedule-content').innerHTML=view==='day'?table(day):D.map((d,i)=>'<article class="week-block" data-day-block="'+i+'"><div class="week-heading"><h3 class="week-title">'+d.label+(i===today?' <span>СЬОГОДНІ</span>':'')+'</h3><div class="week-actions">'+perDayFilter(i)+'<button class="text-button" type="button" data-print-day="'+i+'">Друк дня ↗</button></div></div>'+table(i)+'</article>').join('');
$('#print-button').innerHTML='<span aria-hidden="true">↗</span> '+(view==='week'?'Друк тижня':'Друк / PDF');
$('#subject-filter').value=subject;
applyFilters();updateLive(true);syncUrl();renderSection();}
function syncUrl(){const query=new URLSearchParams();if(grade!=='all')query.set('class',grade);if(view==='week')query.set('view','week');if(!autoDay)query.set('day',D[day].id);const str=query.toString();history.replaceState(null,'',location.pathname+(str?'?'+str:'')+'#'+section);document.title=(section==='bells'?'Дзвінки':grade==='all'?'Розклад 5–9 класів':grade+' клас — розклад')+' · Почуйки 2026–2027';}
function renderSection(){section=location.hash==='#bells'?'bells':'schedule';$('#schedule').hidden=section!=='schedule';$('#bells').hidden=section!=='bells';$$('[data-nav]').forEach(a=>{if(a.dataset.nav===section)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});syncUrl();}
function applyFilters(){let count=0;$$('#schedule-content [data-subject]').forEach(btn=>{const row=btn.closest('[data-row-day]');const local=dayFilters[row?.dataset.rowDay]||'';const target=subject||local;const match=btn.dataset.subject===target;btn.classList.toggle('is-match',Boolean(target)&&match);btn.classList.toggle('is-dim',Boolean(target)&&!match);btn.setAttribute('aria-pressed',String(Boolean(target)&&match));if(target&&match)count++;});$('#filter-result').textContent=subject||Object.values(dayFilters).some(Boolean)?'Знайдено уроків: '+count:'';}
function renderBells(){ $('#bells-content').innerHTML=B.map((b,i)=>'<div class="bell-row" data-bell="'+b.lesson+'"><span class="bell-number">'+b.lesson+'</span><span class="bell-name">'+b.lesson+'-й урок<small></small></span><span class="bell-hours">'+b.start+' <span aria-hidden="true">—</span> '+b.end+'</span></div>'+(i<B.length-1?'<div class="bell-break '+(i===1||i===2?'large':'')+'" data-break="'+b.lesson+'"><span>'+(i===1||i===2?'Велика перерва':'Перерва')+'</span><span>'+((hhmmSeconds(B[i+1].start)-hhmmSeconds(b.end))/60)+' хв</span></div>':'')).join('');}
function text(selector,value){const node=$(selector);if(node&&node.textContent!==value)node.textContent=value;}
function updateLive(force=false){const now=clock.now(),p=kyivParts(now),key=Math.floor(now/1000);if(!force&&key===lastSecond)return;lastSecond=key;
const time=timeFormatter.format(now);$('#clock').innerHTML=time.slice(0,5)+'<span>'+time.slice(5)+'</span>';$('#clock').dateTime=new Date(now).toISOString();text('#date',dateFormatter.format(now));text('#sync-status',clock.source);
if(lastDate&&p.dateKey!==lastDate){today=p.weekday-1;if(autoDay)day=today>=0&&today<5?today:0;lastDate=p.dateKey;render();return;}lastDate=p.dateKey;
const state=schoolState(now,C,section==='bells'?'all':grade),w=silenceWindow(now);
text('#live-kind',state.kind==='lesson'?'ЗАРАЗ У ШКОЛІ':state.kind==='break'?'ЧАС ПЕРЕРВИ':'ШКІЛЬНИЙ ДЕНЬ');text('#live-title',w.active?'Загальнонаціональна хвилина мовчання':state.title);text('#live-detail',w.active?'Вшановуємо пам’ять усіх загиблих унаслідок війни.':state.detail);text('#countdown-label',w.active?'До завершення':state.timerLabel);text('#countdown',w.active?durationLabel(w.remaining):state.remaining?durationLabel(state.remaining):'—');$('#live-progress').style.width=(w.active?w.elapsed/60:state.progress)*100+'%';
$('#silence').classList.toggle('is-active',w.active);$('#silence-countdown').hidden=!w.active;text('#silence-countdown',durationLabel(w.remaining));text('#silence-title',w.active?'Пам’ятаємо. Вшановуємо.':'Хвилина мовчання');text('#silence-detail',w.active?'09:00–09:01 · Київський час':'Щодня о 09:00–09:01. Вшановуємо пам’ять загиблих.');
const liveKey=[p.dateKey,state.kind,state.lesson,state.nextLesson,grade,view,day,section].join('|');if(force||liveKey!==lastLive){lastLive=liveKey;$$('#schedule-content [data-row-day]').forEach(row=>{const current=Number(row.dataset.rowDay)===state.dayIndex&&Number(row.dataset.lesson)===state.lesson;const upcoming=Number(row.dataset.rowDay)===state.dayIndex&&Number(row.dataset.lesson)===state.nextLesson;row.classList.toggle('is-current',current);row.classList.toggle('is-upcoming',upcoming);row.querySelector('.row-state').textContent=current?'ЗАРАЗ':upcoming?'НАСТУПНИЙ':'';if(current)row.setAttribute('aria-current','time');else row.removeAttribute('aria-current');});
const globalState=schoolState(now,C);$$('[data-bell]').forEach(row=>{const active=+row.dataset.bell===globalState.lesson;row.classList.toggle('is-current',active);row.querySelector('small').textContent=active?'Триває зараз':'';});$$('[data-break]').forEach(row=>row.classList.toggle('is-current',globalState.kind==='break'&& +row.dataset.break===globalState.nextLesson-1));}
$$('#schedule-content .is-current .row-state').forEach(node=>{node.textContent='ЗАРАЗ · '+durationLabel(state.remaining);});}
function printView(printDay=null){const stage=$('#print-stage');let heading='Розклад уроків',content='';if(section==='bells'&&printDay===null){heading='Розклад дзвінків';content=$('#bells-content').outerHTML;}else if(printDay!==null){heading=D[printDay].label+' · 5–9 класи';content=table(printDay,true);}else if(view==='week'&&grade!=='all'){heading=grade+' клас · Розклад на тиждень';content=weekMatrix();}else if(view==='week'){content=D.map((d,i)=>'<article class="week-block"><h2>'+d.label+'</h2>'+table(i,true)+'</article>').join('');}else{heading=D[day].label+' · '+(grade==='all'?'5–9 класи':grade+' клас');content=table(day);}
stage.innerHTML='<h1>'+heading+'</h1><p>Почуйківська філія Квітневого ліцею · І семестр · 2026–2027 навчальний рік</p>'+content;stage.querySelectorAll('a,button.subject').forEach(node=>{const span=document.createElement('span');span.textContent=node.textContent.replace(' ↗','');span.className=node.className;node.replaceWith(span);});stage.dataset.ready='true';}
$('#print-button').addEventListener('click',()=>{printView();window.print();});
window.addEventListener('beforeprint',()=>{if($('#print-stage').dataset.ready!=='true')printView();});window.addEventListener('afterprint',()=>{delete $('#print-stage').dataset.ready;$('#print-stage').innerHTML='';});
document.addEventListener('click',event=>{const button=event.target.closest('button,a');if(!button)return;
if(button.dataset.class!==undefined){grade=button.dataset.class;render();}
if(button.dataset.day!==undefined){day=+button.dataset.day;autoDay=false;view='day';render();}
if(button.dataset.view){view=button.dataset.view;render();}
if(button.dataset.gradeLink){event.preventDefault();grade=button.dataset.gradeLink;view='week';render();}
if(button.dataset.subject){const i=button.closest('[data-row-day]').dataset.rowDay;if(view==='week'){dayFilters[i]=dayFilters[i]===button.dataset.subject?'':button.dataset.subject;subject='';$('#subject-filter').value='';const select=$('[data-day-subject="'+i+'"]');if(select)select.value=dayFilters[i];}else{subject=subject===button.dataset.subject?'':button.dataset.subject;$('#subject-filter').value=subject;}applyFilters();}
if(button.dataset.printDay!==undefined){printView(+button.dataset.printDay);window.print();}});
$('#subject-filter').addEventListener('change',event=>{subject=event.target.value;dayFilters={};$$('[data-day-subject]').forEach(s=>s.value='');applyFilters();});
document.addEventListener('change',event=>{if(event.target.dataset.daySubject!==undefined){dayFilters[event.target.dataset.daySubject]=event.target.value;subject='';$('#subject-filter').value='';applyFilters();}});
$('#today-button').addEventListener('click',()=>{today=kyivParts(clock.now()).weekday-1;day=today>=0&&today<5?today:0;autoDay=true;view='day';render();});
$('#back-top').addEventListener('click',event=>{event.preventDefault();window.scrollTo({top:0,behavior:'smooth'});});
window.addEventListener('hashchange',()=>{renderSection();updateLive(true);});
window.addEventListener('popstate',()=>{section=location.hash==='#bells'?'bells':'schedule';const q=new URLSearchParams(location.search),g=(q.get('class')||'').replace(' клас','').trim();grade=/^[5-9]$/.test(g)?g:'all';view=q.get('view')==='week'?'week':'day';const index=D.findIndex(d=>d.id===q.get('day'));autoDay=index<0;day=index<0?(today>=0&&today<5?today:0):index;render();});
renderBells();render();clock.start();setInterval(()=>updateLive(),200);document.addEventListener('visibilitychange',()=>{if(!document.hidden)updateLive(true);});
$('#sound-button').hidden=true;
const player=new SilencePlayer(clock,({state,ready,active,error,otherTab})=>{const blocked=active&&(state==='blocked'||state==='unsupported');$('#sound-button').hidden=!blocked;$('#sound-button').disabled=state==='unsupported';$('#sound-button').setAttribute('aria-pressed',String(ready));text('#sound-button',state==='unsupported'?'Звук недоступний':'Увімкнути метроном');
text('#audio-help',state==='unsupported'?'Цей браузер не підтримує звук метронома.':active&&otherTab?'Метроном відтворюється в іншій відкритій вкладці сайту.':blocked?'Браузер призупинив звук. Торкніться сторінки — метроном долучиться з поточної секунди.':ready?'Звук готовий · Метроном автоматично звучатиме лише о 09:00–09:01.':state==='loading'?'Підготовка метронома…':'Звук активується після звичайного дотику до сайту. Тримайте сторінку відкритою, а пристрій — активним.');
});
$('#sound-button').addEventListener('click',()=>player.enable());
