export const KYIV_ZONE='Europe/Kyiv';
const formatter=new Intl.DateTimeFormat('en-CA',{timeZone:KYIV_ZONE,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});
export const hhmmSeconds=s=>{const [h,m]=s.split(':').map(Number);return h*3600+m*60;};
export function kyivParts(ms){const p=Object.fromEntries(formatter.formatToParts(new Date(ms)).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));const weekday=new Date(Date.UTC(+p.year,+p.month-1,+p.day)).getUTCDay();return {...p,weekday,dateKey:p.year+'-'+p.month+'-'+p.day,seconds:+p.hour*3600+ +p.minute*60+ +p.second+((ms%1000)+1000)%1000/1000};}
export function silenceWindow(ms){const p=kyivParts(ms),start=9*3600,elapsed=p.seconds-start;return {active:elapsed>=0&&elapsed<60,elapsed:Math.max(0,Math.min(60,elapsed)),remaining:Math.max(0,60-elapsed),untilStart:start-p.seconds,dateKey:p.dateKey};}
export function playbackPlan(ms,audioTime=0){const w=silenceWindow(ms);if(!w.active&&!(w.untilStart>0&&w.untilStart<=120))return null;const delay=Math.max(0,w.untilStart),offset=w.active?w.elapsed:0;return {dateKey:w.dateKey,offset,duration:60-offset,when:audioTime+delay,stopAt:audioTime+delay+60-offset,endEpoch:ms+(delay+60-offset)*1000};}
export function durationLabel(seconds){const n=Math.max(0,Math.ceil(seconds));const h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=n%60;return h?h+':'+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0'):String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');}
export function schoolState(ms,config,grade='all'){const p=kyivParts(ms);const dayIndex=p.weekday-1;
if(dayIndex<0||dayIndex>4)return {kind:'weekend',dayIndex,lesson:null,remaining:0,progress:0,title:'Сьогодні вихідний',detail:'Наступний навчальний день — понеділок, о 08:30',timerLabel:'Час відпочити'};
const rows=config.scheduleRows.filter(r=>r.day===config.dayOrder[dayIndex].label);const gradeIndex=grade==='all'?-1:Number(grade)-5;const lessons=config.bellSchedule.filter(b=>{const row=rows.find(r=>r.lesson===b.lesson);return row&&(gradeIndex<0?row.classes.some(Boolean):Boolean(row.classes[gradeIndex]));});
const active=lessons.find(b=>p.seconds>=hhmmSeconds(b.start)&&p.seconds<hhmmSeconds(b.end));
if(active){const start=hhmmSeconds(active.start),end=hhmmSeconds(active.end);const subject=gradeIndex<0?'':rows.find(r=>r.lesson===active.lesson).classes[gradeIndex];return {kind:'lesson',dayIndex,lesson:active.lesson,remaining:end-p.seconds,progress:(p.seconds-start)/(end-start),title:subject||active.lesson+'-й урок триває',detail:(subject?active.lesson+'-й урок · ':'5–9 класи · ')+active.start+'–'+active.end,timerLabel:'До кінця уроку'};}
const next=lessons.find(b=>hhmmSeconds(b.start)>p.seconds);
if(next){const previous=lessons.filter(b=>hhmmSeconds(b.end)<=p.seconds).at(-1);const start=previous?hhmmSeconds(previous.end):0,end=hhmmSeconds(next.start);return {kind:previous?'break':'before',dayIndex,lesson:null,nextLesson:next.lesson,remaining:end-p.seconds,progress:previous?(p.seconds-start)/(end-start):0,title:previous?'Триває перерва':'Навчальний день попереду',detail:'Наступний: '+next.lesson+'-й урок о '+next.start,timerLabel:'До початку уроку'};}
return {kind:'after',dayIndex,lesson:null,remaining:0,progress:1,title:'Уроки на сьогодні завершено',detail:gradeIndex<0?'Гарного відпочинку! Перегляньте розклад на наступний день.':grade+' клас · Усі уроки на сьогодні завершилися',timerLabel:'До зустрічі'};
}